apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-a
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  description: Project A – Applikationen und Namespace-Konfiguration
  sourceRepos:
    - https://github.com/chriwo42-lang/ocp-workloads.git
    - https://github.com/chriwo42-lang/my-app.git
    - https://github.com/chriwo42-lang/your-app.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: project-a-*
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  roles:
    - name: project-a-admin
      description: Vollzugriff auf alle ArgoCD Apps in project-a (nur cluster-admins)
      policies:
        - p, proj:project-a:project-a-admin, applications, *, project-a/*, allow
      groups:
        - cluster-admins
