apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: project-b-my-app-namespace
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: project-b
  sources:
    - repoURL: https://github.com/chriwo42-lang/ocp-workloads.git
      targetRevision: main
      path: charts/namespace-config
      helm:
        valueFiles:
          - $values/apps/project-b/my-app/values.yaml
    - repoURL: https://github.com/chriwo42-lang/ocp-workloads.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: project-b-my-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
