{{- if not .Values.namespace }}
  {{- fail "namespace ist ein Pflichtfeld und muss in values.yaml gesetzt werden" }}
{{- end }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/managed-by: argocd
    {{- if .Values.project }}
    app.kubernetes.io/part-of: {{ .Values.project }}
    {{- end }}
    {{- if .Values.displayName }}
    openshift.io/display-name: {{ .Values.displayName | quote }}
    {{- end }}
