{{- $ns := .Values.namespace }}

{{- range .Values.rbac.adminGroups }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ . }}-admin
  namespace: {{ $ns }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: Group
    name: {{ . }}
    apiGroup: rbac.authorization.k8s.io
{{- end }}

{{- range .Values.rbac.editGroups }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ . }}-edit
  namespace: {{ $ns }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
  - kind: Group
    name: {{ . }}
    apiGroup: rbac.authorization.k8s.io
{{- end }}

{{- range .Values.rbac.viewGroups }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ . }}-view
  namespace: {{ $ns }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - kind: Group
    name: {{ . }}
    apiGroup: rbac.authorization.k8s.io
{{- end }}

{{- range .Values.rbac.adminUsers }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ . }}-admin
  namespace: {{ $ns }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
  - kind: User
    name: {{ . }}
    apiGroup: rbac.authorization.k8s.io
{{- end }}

{{- range .Values.rbac.editUsers }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ . }}-edit
  namespace: {{ $ns }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
  - kind: User
    name: {{ . }}
    apiGroup: rbac.authorization.k8s.io
{{- end }}
