apiVersion: argoproj.io/v1beta1
kind: Application
metadata:
  name: project-a-my-app
  namespace: openshift-gitops
  annotations:
    # Wave 1: eigentliche App erst nach Namespace-Konfiguration deployen
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: project-a
  source:
    # App-Repo der Entwickler
    repoURL: https://github.com/chriwo42-lang/my-app.git
    targetRevision: main
    path: helm
    helm:
      releaseName: my-app
      # values.yaml liegt im App-Repo selbst
      # Für environment-spezifische Overrides: valueFiles hinzufügen
  destination:
    server: https://kubernetes.default.svc
    namespace: project-a-my-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
