apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: project-b-appproject
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: platform
  sources:
    - repoURL: https://github.com/chriwo42-lang/ocp-workloads.git
      targetRevision: main
      path: charts/project-config
      helm:
        valueFiles:
          - $values/apps/project-b/appproject-values.yaml
    - repoURL: https://github.com/chriwo42-lang/ocp-workloads.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
