apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: team-b
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    # Team-B Mitglieder.
    # Zuweisung zu Namespaces: rbac.editGroups in app/values.yaml
    # ArgoCD-Zugriff: developerTeams in appproject-values.yaml
users:
  - editor
