apiVersion: user.openshift.io/v1
kind: Group
metadata:
  name: team-c
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    # Team-C Mitglieder.
    # Rolle je App konfigurierbar via rbac.adminGroups / rbac.editGroups / rbac.viewGroups
users:
  - charlie
